@{
    PresetName = 'tiny11-dev'
    Description = 'Apply a tiny11 Dev Edition-like cleanup and settings profile to an already installed Windows system.'

    AppIdentities = @(
        'Clipchamp.Clipchamp'
        'Microsoft.BingNews'
        'Microsoft.BingSearch'
        'Microsoft.BingWeather'
        'Microsoft.GamingApp'
        'Microsoft.GetHelp'
        'Microsoft.Getstarted'
        'Microsoft.Microsoft3DViewer'
        'Microsoft.MicrosoftOfficeHub'
        'Microsoft.MicrosoftSolitaireCollection'
        'Microsoft.MicrosoftStickyNotes'
        'Microsoft.Office.OneNote'
        'Microsoft.OfficePushNotificationUtility'
        'Microsoft.People'
        'Microsoft.PowerAutomateDesktop'
        'Microsoft.StartExperiencesApp'
        'Microsoft.Todos'
        'Microsoft.Wallet'
        'Microsoft.Windows.CrossDevice'
        'Microsoft.Windows.DevHome'
        'Microsoft.WindowsAlarms'
        'Microsoft.WindowsCamera'
        'microsoft.windowscommunicationsapps'
        'Microsoft.WindowsFeedbackHub'
        'Microsoft.WindowsMaps'
        'Microsoft.WindowsSoundRecorder'
        'Microsoft.Xbox.TCUI'
        'Microsoft.XboxApp'
        'Microsoft.XboxGamingOverlay'
        'Microsoft.XboxGameOverlay'
        'Microsoft.XboxIdentityProvider'
        'Microsoft.XboxSpeechToTextOverlay'
        'Microsoft.YourPhone'
        'Microsoft.ZuneMusic'
        'Microsoft.ZuneVideo'
        'MicrosoftCorporationII.MicrosoftFamily'
        'MicrosoftCorporationII.QuickAssist'
        'MicrosoftTeams'
        'Microsoft.549981C3F5F10'
        'MSTeams'
        'Microsoft.OutlookForWindows'
        'Microsoft.Windows.Teams'
        'Microsoft.Copilot'
        'Microsoft.Windows.Copilot'
        'Microsoft.MicrosoftPCManager'
    )

    SettingsActions = @(
        'VisualEffects'
        'FileExplorerDeveloper'
        'SponsoredApps'
        'DisableOneDriveBackup'
        'Telemetry'
        'DisableWidgets'
        'DisableSearchHighlights'
        'DisableXboxServices'
        'DisableExtraServices'
        'WindowsSearchManual'
        'LockScreenSpotlight'
        'EdgeOptimization'
        'TraditionalContextMenu'
        'DeveloperContextMenu'
        'WindowsUpdate'
        'RemoveOneDriveSetup'
        'RemovePCManager'
        'RemoveExtendedWallpapers'
    )

    HighRiskActions = @(
        'RemoveExtendedWallpapers'
    )
}
